from __future__ import annotations

import importlib.util
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
PROBE_PATH = ROOT / "scripts" / "benchmarks" / "shared" / "check_public_sanitization.py"
spec = importlib.util.spec_from_file_location("check_public_sanitization", PROBE_PATH)
assert spec and spec.loader
probe = importlib.util.module_from_spec(spec)
sys.modules[spec.name] = probe
spec.loader.exec_module(probe)


class PublicSanitizationTests(unittest.TestCase):
    def init_repo(self, root: Path) -> None:
        subprocess.run(["git", "init"], cwd=root, check=True, stdout=subprocess.PIPE)

    def test_detects_private_identifier_in_public_file(self) -> None:
        with tempfile.TemporaryDirectory() as raw:
            root = Path(raw)
            self.init_repo(root)
            token = probe.banned_tokens()[0].token
            (root / "README.md").write_text(f"private={token}\n")
            violations = probe.scan(root)
            self.assertEqual(len(violations), 1)
            self.assertEqual(violations[0]["where"], "line 1")

    def test_detects_private_identifier_in_public_path(self) -> None:
        with tempfile.TemporaryDirectory() as raw:
            root = Path(raw)
            self.init_repo(root)
            token = probe.banned_tokens()[1].token
            path = root / f"{token}.md"
            path.write_text("sample\n")
            violations = probe.scan(root)
            self.assertEqual(len(violations), 1)
            self.assertEqual(violations[0]["where"], "path")

    def test_ignores_local_results(self) -> None:
        with tempfile.TemporaryDirectory() as raw:
            root = Path(raw)
            self.init_repo(root)
            token = probe.banned_tokens()[2].token
            results = root / "results"
            results.mkdir()
            (results / "private.md").write_text(token)
            self.assertEqual(probe.scan(root), [])

    def test_scans_public_evidence_directory(self) -> None:
        with tempfile.TemporaryDirectory() as raw:
            root = Path(raw)
            self.init_repo(root)
            token = probe.banned_tokens()[3].token
            evidence = root / "benchmarks" / "real-agent-routing" / "evidence" / "public-smoke"
            evidence.mkdir(parents=True)
            (evidence / "summary.md").write_text(f"private={token}\n")

            violations = probe.scan(root)

            self.assertEqual(len(violations), 1)
            self.assertEqual(violations[0]["where"], "line 1")

    def test_rejects_png_text_metadata_even_without_known_private_identifier(self) -> None:
        with tempfile.TemporaryDirectory() as raw:
            root = Path(raw)
            self.init_repo(root)

            def chunk(kind: bytes, payload: bytes) -> bytes:
                return len(payload).to_bytes(4, "big") + kind + payload + b"\0\0\0\0"

            png = (
                b"\x89PNG\r\n\x1a\n"
                + chunk(b"tEXt", b"Comment\0generated by local tool")
                + chunk(b"IEND", b"")
            )
            image = root / "docs" / "asset.png"
            image.parent.mkdir()
            image.write_bytes(png)

            violations = probe.scan(root)

            self.assertEqual(len(violations), 1)
            self.assertEqual(violations[0]["where"], "png metadata tEXt")
            self.assertEqual(violations[0]["label"], "png_metadata_forbidden")

    def test_rejects_png_exif_metadata(self) -> None:
        with tempfile.TemporaryDirectory() as raw:
            root = Path(raw)
            self.init_repo(root)

            def chunk(kind: bytes, payload: bytes) -> bytes:
                return len(payload).to_bytes(4, "big") + kind + payload + b"\0\0\0\0"

            png = b"\x89PNG\r\n\x1a\n" + chunk(b"eXIf", b"metadata") + chunk(b"IEND", b"")
            image = root / "docs" / "asset.png"
            image.parent.mkdir()
            image.write_bytes(png)

            violations = probe.scan(root)

            self.assertEqual(len(violations), 1)
            self.assertEqual(violations[0]["where"], "png metadata eXIf")

    def test_rejects_malformed_png_text_metadata_chunks(self) -> None:
        cases = [
            (b"zTXt", b"Comment\0\x01unsupported compression"),
            (b"zTXt", b"malformed without separator"),
            (b"iTXt", b"bad"),
        ]
        for kind, payload in cases:
            with self.subTest(kind=kind, payload=payload):
                with tempfile.TemporaryDirectory() as raw:
                    root = Path(raw)
                    self.init_repo(root)

                    def chunk(chunk_kind: bytes, chunk_payload: bytes) -> bytes:
                        return len(chunk_payload).to_bytes(4, "big") + chunk_kind + chunk_payload + b"\0\0\0\0"

                    image = root / "docs" / f"{kind.decode('ascii')}.png"
                    image.parent.mkdir()
                    image.write_bytes(b"\x89PNG\r\n\x1a\n" + chunk(kind, payload) + chunk(b"IEND", b""))

                    violations = probe.scan(root)

                    self.assertEqual(len(violations), 1)
                    self.assertEqual(violations[0]["where"], f"png metadata {kind.decode('ascii')}")
                    self.assertEqual(violations[0]["label"], "png_metadata_forbidden")

    def test_rejects_absolute_paths_in_public_evidence_json(self) -> None:
        with tempfile.TemporaryDirectory() as raw:
            root = Path(raw)
            self.init_repo(root)
            evidence = root / "benchmarks" / "real-agent-routing" / "evidence" / "public-smoke"
            evidence.mkdir(parents=True)
            (evidence / "summary.sanitized.json").write_text('{"path": "/Users/example/private"}\n')

            violations = probe.scan(root)

            self.assertIn("evidence_absolute_private_path", {item["label"] for item in violations})

    def test_rejects_unapproved_target_label_in_public_evidence_json(self) -> None:
        with tempfile.TemporaryDirectory() as raw:
            root = Path(raw)
            self.init_repo(root)
            evidence = root / "benchmarks" / "real-agent-routing" / "evidence" / "codex-ad-smoke-anonymized"
            evidence.mkdir(parents=True)
            (evidence / "runs.sanitized.jsonl").write_text('{"target_label": "Specific Internal Repo"}\n')

            violations = probe.scan(root)

            self.assertIn("evidence_unapproved_target_label", {item["label"] for item in violations})

    def test_future_public_evidence_schema_is_not_forced_to_codex_smoke_shape(self) -> None:
        with tempfile.TemporaryDirectory() as raw:
            root = Path(raw)
            self.init_repo(root)
            evidence = root / "benchmarks" / "real-agent-routing" / "evidence" / "future-public-study"
            evidence.mkdir(parents=True)
            (evidence / "summary.sanitized.json").write_text('{"title": "Future public study", "new_public_metric": 1}\n')

            self.assertEqual(probe.scan(root), [])

    def test_rejects_unexpected_codex_smoke_evidence_json_field(self) -> None:
        with tempfile.TemporaryDirectory() as raw:
            root = Path(raw)
            self.init_repo(root)
            evidence = root / "benchmarks" / "real-agent-routing" / "evidence" / "codex-ad-smoke-anonymized"
            evidence.mkdir(parents=True)
            (evidence / "summary.sanitized.json").write_text('{"title": "ok", "unexpected": true}\n')

            violations = probe.scan(root)

            self.assertEqual(len(violations), 1)
            self.assertEqual(violations[0]["label"], "evidence_unexpected_json_field")

    def test_rejects_unexpected_codex_smoke_source_run_field(self) -> None:
        with tempfile.TemporaryDirectory() as raw:
            root = Path(raw)
            self.init_repo(root)
            evidence = root / "benchmarks" / "real-agent-routing" / "evidence" / "codex-ad-smoke-anonymized"
            evidence.mkdir(parents=True)
            (evidence / "source.sanitized.json").write_text('{"runs": [{"target_label": "Commerce Web Frontend", "unexpected": true}]}\n')

            violations = probe.scan(root)

            self.assertEqual(len(violations), 1)
            self.assertEqual(violations[0]["label"], "evidence_unexpected_json_field")
            self.assertIn(".runs[0].unexpected", violations[0]["where"])

    def test_rejects_unexpected_codex_smoke_claim_row_field(self) -> None:
        with tempfile.TemporaryDirectory() as raw:
            root = Path(raw)
            self.init_repo(root)
            evidence = root / "benchmarks" / "real-agent-routing" / "evidence" / "codex-ad-smoke-anonymized"
            evidence.mkdir(parents=True)
            (evidence / "claim-readiness.sanitized.json").write_text('{"rows": [{"target_label": "Commerce Web Frontend", "unexpected": true}]}\n')

            violations = probe.scan(root)

            self.assertEqual(len(violations), 1)
            self.assertEqual(violations[0]["label"], "evidence_unexpected_json_field")
            self.assertIn(".rows[0].unexpected", violations[0]["where"])


if __name__ == "__main__":
    unittest.main()
